### ISSUE TITLE
Server segfaults on isValid()

### ISSUE THREAD

**Issue by KennethWhite** [COsborn2/ChatServer#26]
Server appears to segfault when calling the commands.c isValid() command when the client tries to join a room.

**Comment by ArrinTorno** [comment]
Problem within isValidCommand:
`Line 48: char temporaryS[strlen(toParse)+1];`
C doesn't allow stack arrays with a dynamic length, like you would get from this function. You would need to change this to
    `char *temporaryS = malloc(strlen(toParse) + 1);`
and then later add
    `free(temporaryS);`
    `temporaryS = NULL;`
I'm surprised the compiler didn't stop this but if it did try this the memory should be screwy.
